name = "sikesra"
compatibility_date = "2026-05-09"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sikesra"
database_id = "78f08b97-305a-431b-9f7c-9f1c3bbb4551"

[[d1_databases]]
binding = "SIKESRA_DB"
database_name = "sikesra"
database_id = "78f08b97-305a-431b-9f7c-9f1c3bbb4551"


[[r2_buckets]]
binding = "SIKESRA_DOCUMENTS"
bucket_name = "sikesra"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "sikesra"

[[kv_namespaces]]
binding = "SESSION"

[observability]
enabled = true
