-- SIKESRA seed data generated by sikesra-seed.mjs

INSERT OR REPLACE INTO awcms_sikesra_settings (
  id, tenant_id, site_id, public_enabled, public_title, public_description,
  data_scope_note, official_contact, small_cell_threshold, max_upload_bytes,
  allowed_mime_types_json, export_max_sync_rows,
  require_reason_for_highly_restricted_download, feature_flags_json
) VALUES (
  'sikesra-settings-default', '00000000-0000-0000-0000-000000000001', 'main', 0,
  'SIKESRA', 'Sistem Informasi Kesejahteraan Rakyat',
  'Halaman publik hanya menampilkan data agregat aman publik.', '',
  5, 10485760,
  '["application/pdf","image/jpeg","image/png","image/webp"]', 5000,
  1,
  '{"publicSummary":true,"verificationWorkflow":true,"documentAudit":true,"importStaging":true,"exportJobs":true}'
);

INSERT OR IGNORE INTO awcms_sikesra_object_types (
  code, tenant_id, site_id, name, description, entity_kind, sort_order
) VALUES (
  '01', '00000000-0000-0000-0000-000000000001', 'main',
  'Rumah Ibadah', 'Bangunan rumah ibadah dan sarana pendukungnya.',
  'building', 10
);

INSERT OR IGNORE INTO awcms_sikesra_object_types (
  code, tenant_id, site_id, name, description, entity_kind, sort_order
) VALUES (
  '02', '00000000-0000-0000-0000-000000000001', 'main',
  'Lembaga Keagamaan', 'Lembaga keagamaan tingkat lokal sampai kabupaten.',
  'institution', 20
);

INSERT OR IGNORE INTO awcms_sikesra_object_types (
  code, tenant_id, site_id, name, description, entity_kind, sort_order
) VALUES (
  '03', '00000000-0000-0000-0000-000000000001', 'main',
  'Pendidikan Keagamaan', 'Satuan pendidikan keagamaan formal dan non-formal.',
  'institution', 30
);

INSERT OR IGNORE INTO awcms_sikesra_object_types (
  code, tenant_id, site_id, name, description, entity_kind, sort_order
) VALUES (
  '04', '00000000-0000-0000-0000-000000000001', 'main',
  'Lembaga Kesejahteraan Sosial', 'Lembaga sosial, bantuan, dan pengasuhan.',
  'institution', 40
);

INSERT OR IGNORE INTO awcms_sikesra_object_types (
  code, tenant_id, site_id, name, description, entity_kind, sort_order
) VALUES (
  '05', '00000000-0000-0000-0000-000000000001', 'main',
  'Guru Agama', 'Data guru agama lintas satuan dan pembinaan.',
  'person', 50
);

INSERT OR IGNORE INTO awcms_sikesra_object_types (
  code, tenant_id, site_id, name, description, entity_kind, sort_order
) VALUES (
  '06', '00000000-0000-0000-0000-000000000001', 'main',
  'Anak Yatim', 'Registri anak yatim, piatu, dan yatim piatu.',
  'person', 60
);

INSERT OR IGNORE INTO awcms_sikesra_object_types (
  code, tenant_id, site_id, name, description, entity_kind, sort_order
) VALUES (
  '07', '00000000-0000-0000-0000-000000000001', 'main',
  'Disabilitas', 'Registri penyandang disabilitas dan kebutuhan dukungan.',
  'person', 70
);

INSERT OR IGNORE INTO awcms_sikesra_object_types (
  code, tenant_id, site_id, name, description, entity_kind, sort_order
) VALUES (
  '08', '00000000-0000-0000-0000-000000000001', 'main',
  'Lansia Terlantar', 'Registri lansia terlantar, rawan terlantar, dan mandiri berisiko.',
  'person', 80
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-01-01', '00000000-0000-0000-0000-000000000001', 'main',
  '01', '01',
  'Masjid', 10
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-01-02', '00000000-0000-0000-0000-000000000001', 'main',
  '01', '02',
  'Musholla', 20
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-01-03', '00000000-0000-0000-0000-000000000001', 'main',
  '01', '03',
  'Surau', 30
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-01-04', '00000000-0000-0000-0000-000000000001', 'main',
  '01', '04',
  'Gereja', 40
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-01-05', '00000000-0000-0000-0000-000000000001', 'main',
  '01', '05',
  'Pura', 50
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-01-06', '00000000-0000-0000-0000-000000000001', 'main',
  '01', '06',
  'Wihara', 60
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-01-07', '00000000-0000-0000-0000-000000000001', 'main',
  '01', '07',
  'Klenteng', 70
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-01-99', '00000000-0000-0000-0000-000000000001', 'main',
  '01', '99',
  'Lainnya', 999
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-02-01', '00000000-0000-0000-0000-000000000001', 'main',
  '02', '01',
  'Islam', 10
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-02-02', '00000000-0000-0000-0000-000000000001', 'main',
  '02', '02',
  'Kristen', 20
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-02-03', '00000000-0000-0000-0000-000000000001', 'main',
  '02', '03',
  'Katolik', 30
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-02-04', '00000000-0000-0000-0000-000000000001', 'main',
  '02', '04',
  'Hindu', 40
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-02-05', '00000000-0000-0000-0000-000000000001', 'main',
  '02', '05',
  'Buddha', 50
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-02-06', '00000000-0000-0000-0000-000000000001', 'main',
  '02', '06',
  'Konghucu', 60
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-02-99', '00000000-0000-0000-0000-000000000001', 'main',
  '02', '99',
  'Lainnya', 999
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-03-01', '00000000-0000-0000-0000-000000000001', 'main',
  '03', '01',
  'TPA/TPQ', 10
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-03-02', '00000000-0000-0000-0000-000000000001', 'main',
  '03', '02',
  'Pondok Pesantren', 20
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-03-99', '00000000-0000-0000-0000-000000000001', 'main',
  '03', '99',
  'Lainnya', 999
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-04-01', '00000000-0000-0000-0000-000000000001', 'main',
  '04', '01',
  'BAZNAS', 10
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-04-02', '00000000-0000-0000-0000-000000000001', 'main',
  '04', '02',
  'PWRI', 20
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-04-03', '00000000-0000-0000-0000-000000000001', 'main',
  '04', '03',
  'Panti Asuhan', 30
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-04-04', '00000000-0000-0000-0000-000000000001', 'main',
  '04', '04',
  'Panti Yatim', 40
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-04-05', '00000000-0000-0000-0000-000000000001', 'main',
  '04', '05',
  'Panti Jompo', 50
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-04-06', '00000000-0000-0000-0000-000000000001', 'main',
  '04', '06',
  'Rukun Kematian', 60
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-04-07', '00000000-0000-0000-0000-000000000001', 'main',
  '04', '07',
  'Majelis Taklim', 70
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-04-99', '00000000-0000-0000-0000-000000000001', 'main',
  '04', '99',
  'LKS Lainnya', 999
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-05-01', '00000000-0000-0000-0000-000000000001', 'main',
  '05', '01',
  'Rumahan', 10
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-05-02', '00000000-0000-0000-0000-000000000001', 'main',
  '05', '02',
  'Lembaga', 20
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-05-99', '00000000-0000-0000-0000-000000000001', 'main',
  '05', '99',
  'Lainnya', 999
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-06-01', '00000000-0000-0000-0000-000000000001', 'main',
  '06', '01',
  'Yatim', 10
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-06-02', '00000000-0000-0000-0000-000000000001', 'main',
  '06', '02',
  'Piatu', 20
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-06-03', '00000000-0000-0000-0000-000000000001', 'main',
  '06', '03',
  'Yatim Piatu', 30
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-07-01', '00000000-0000-0000-0000-000000000001', 'main',
  '07', '01',
  'Fisik', 10
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-07-02', '00000000-0000-0000-0000-000000000001', 'main',
  '07', '02',
  'Intelektual', 20
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-07-03', '00000000-0000-0000-0000-000000000001', 'main',
  '07', '03',
  'Mental', 30
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-07-04', '00000000-0000-0000-0000-000000000001', 'main',
  '07', '04',
  'Sensorik', 40
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-08-01', '00000000-0000-0000-0000-000000000001', 'main',
  '08', '01',
  'Terlantar', 10
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-08-02', '00000000-0000-0000-0000-000000000001', 'main',
  '08', '02',
  'Rawan Terlantar', 20
);

INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  'seed-08-03', '00000000-0000-0000-0000-000000000001', 'main',
  '08', '03',
  'Mandiri dengan Risiko', 30
);
