-- Migration Skeleton: Seed tenant-level Stitch import controls
--
-- Settings schema (stored as JSON string in settings.value):
-- {
--   "enabled": false,
--   "mode": "hybrid",
--   "max_input_kb": 512,
--   "allow_raw_html_fallback": true,
--   "allowed_source_formats": ["html", "zip"],
--   "track_import_history": true
-- }

-- Stitch Import removed from the maintained product surface.
-- Historical migration retained as a no-op to preserve timestamp ordering.
