-- Migration: Fix Supabase Advisor Issues
-- Generated by Antigravity
-- Date: 2026-02-09

-- 1. Fix: Function `public.handle_storage_sync` has a role mutable search_path
-- Issue: Security best practice requires `security definer` functions to have a fixed search_path.
-- Resolution: Set search_path to 'public'.
DO $$
DECLARE
  func_sig text;
BEGIN
  -- Dynamically find the function signature to avoid errors if args don't match or function is missing locally
  SELECT oid::regprocedure::text INTO func_sig
  FROM pg_proc
  WHERE proname = 'handle_storage_sync'
  AND pronamespace = 'public'::regnamespace
  LIMIT 1;

  IF func_sig IS NOT NULL THEN
    RAISE NOTICE 'Altering function % to set fixed search_path', func_sig;
    EXECUTE 'ALTER FUNCTION ' || func_sig || ' SET search_path = public';
  ELSE
    RAISE NOTICE 'Function public.handle_storage_sync not found locally. Skipping fix.';
  END IF;
END $$;


-- 2. Fix: Table `public.orders` RLS policy performance
-- Issue: `auth.uid()` or similar functions are re-evaluated for every row in the policy "Enable insert for authenticated users with permission".
-- Resolution: Wrap auth calls in `(select ...)` to cache the result per statement.

-- NOTE: The `orders` table and this specific policy were not found in the local migrations.
-- This suggests they exist on the remote project but haven't been pulled locally.
-- Below is a TEMPLATE to fix this. usage:
-- 1. Uncomment the block.
-- 2. Verify the `WITH CHECK` condition matches your actual logic.
-- 3. Ensure `(select auth.uid())` is used instead of `auth.uid()`.

/*
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'orders') THEN
        -- Drop the old policy
        DROP POLICY IF EXISTS "Enable insert for authenticated users with permission" ON public.orders;
        
        -- Recreate with optimized syntax
        -- IMPORTANT: Replace the condition below with your ACTUAL policy logic
        CREATE POLICY "Enable insert for authenticated users with permission" ON public.orders
        AS PERMISSIVE FOR INSERT
        TO authenticated
        WITH CHECK (
            -- EXAMPLE:
            -- (select auth.uid()) = user_id
            
            -- Placeholder condition (CHANGE THIS):
            true
        );
        
        RAISE NOTICE 'Optimized RLS policy for public.orders';
    ELSE
        RAISE NOTICE 'Table public.orders not found. Skipping policy fix.';
    END IF;
END $$;
*/
