#!/usr/bin/env node

/**
 * Seed the remote (or local) D1 database with SIKESRA baseline data.
 *
 * Usage:
 *   node scripts/sikesra-seed.mjs apply --database <d1-name> [--remote] [--execute]
 *   node scripts/sikesra-seed.sql --database <d1-name> [--remote]
 *
 * Options:
 *   --database <name>  D1 database name (required, or set SIKESRA_D1_DATABASE)
 *   --remote           Target remote D1 (default: --local)
 *   --execute          Actually run the SQL (default: dry-run, prints SQL)
 *   --sql-only         Only print SQL to stdout, don't execute
 */

import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, "..");
const seedsDir = resolve(repoRoot, "packages/plugins/sikesra/seeds");

const TENANT_ID = "00000000-0000-0000-0000-000000000001";
const SITE_ID = "main";

const args = process.argv.slice(2);
const command = args[0] ?? "help";

if (command === "apply") {
	runApply(args.slice(1));
	process.exit(0);
}

if (command === "sql") {
	runSql(args.slice(1));
	process.exit(0);
}

printHelp();
process.exit(command === "help" ? 0 : 1);

function runApply(rest) {
	const database =
		readFlagValue(rest, "--database") ?? process.env.SIKESRA_D1_DATABASE ?? process.env.D1_DATABASE;
	if (!database) {
		process.stderr.write("Missing database name. Pass --database <name> or set SIKESRA_D1_DATABASE.\n");
		process.exit(1);
	}

	const execute = rest.includes("--execute");
	const target = rest.includes("--remote") ? "--remote" : "--local";
	const sql = generateSeedSql();

	if (!execute) {
		process.stdout.write(`Database: ${database}\n`);
		process.stdout.write(`Target: ${target}\n`);
		process.stdout.write(`Execution: dry-run\n\n`);
		process.stdout.write("Generated SQL:\n");
		process.stdout.write(sql);
		process.stdout.write("\n\nPass --execute to apply.\n");
		return;
	}

	const tmpFile = resolve(repoRoot, ".tmp-sikesra-seed.sql");
	writeFileSync(tmpFile, sql);

	process.stdout.write(`Applying seed to ${database} (${target})...\n`);

	const result = spawnSync("npx", ["wrangler", "d1", "execute", database, target, "--file", tmpFile], {
		cwd: repoRoot,
		stdio: "inherit",
	});

	try {
		unlinkSync(tmpFile);
	} catch {
		// ignore
	}

	if (result.status !== 0) process.exit(result.status ?? 1);
	process.stdout.write("Seed applied successfully.\n");
}

function runSql(rest) {
	const sql = generateSeedSql();
	process.stdout.write(sql);
}

function generateSeedSql() {
	const settingsSeed = loadJson("0001_sikesra_settings.seed.json");
	const objectTypesSeed = loadJson("0002_sikesra_object_types.seed.json");
	const objectSubtypesSeed = loadJson("0003_sikesra_object_subtypes.seed.json");

	const sqlParts = [];
	sqlParts.push("-- SIKESRA seed data generated by sikesra-seed.mjs");
	sqlParts.push("BEGIN;");

	// Settings (INSERT OR REPLACE to allow re-seeding)
	const s = settingsSeed.settings;
	const featureFlagsJson = JSON.stringify(s.featureFlags || {});
	const allowedMimeJson = JSON.stringify(s.allowedMimeTypes || []);
	sqlParts.push(`
INSERT OR REPLACE INTO awcms_sikesra_settings (
  id, tenant_id, site_id, public_enabled, public_title, public_description,
  data_scope_note, official_contact, small_cell_threshold, max_upload_bytes,
  allowed_mime_types_json, export_max_sync_rows,
  require_reason_for_highly_restricted_download, feature_flags_json
) VALUES (
  '${escapeSql(s.id)}', '${TENANT_ID}', '${SITE_ID}', ${s.publicEnabled ? 1 : 0},
  '${escapeSql(s.publicTitle)}', '${escapeSql(s.publicDescription)}',
  '${escapeSql(s.dataScopeNote)}', '${escapeSql(s.officialContact)}',
  ${s.smallCellThreshold}, ${s.maxUploadBytes},
  '${escapeSql(allowedMimeJson)}', ${s.exportMaxSyncRows},
  ${s.requireReasonForHighlyRestrictedDownload ? 1 : 0},
  '${escapeSql(featureFlagsJson)}'
);`);

	// Object types (INSERT OR IGNORE to avoid duplicates)
	for (const ot of objectTypesSeed.objectTypes) {
		sqlParts.push(`
INSERT OR IGNORE INTO awcms_sikesra_object_types (
  code, tenant_id, site_id, name, description, entity_kind, sort_order
) VALUES (
  '${escapeSql(ot.code)}', '${TENANT_ID}', '${SITE_ID}',
  '${escapeSql(ot.name)}', ${ot.description ? `'${escapeSql(ot.description)}'` : "NULL"},
  '${escapeSql(ot.entityKind)}', ${ot.sortOrder}
);`);
	}

	// Object subtypes (INSERT OR IGNORE)
	for (const ost of objectSubtypesSeed.objectSubtypes) {
		const id = `seed-${ost.typeCode}-${ost.code}`;
		sqlParts.push(`
INSERT OR IGNORE INTO awcms_sikesra_object_subtypes (
  id, tenant_id, site_id, type_code, code, name, sort_order
) VALUES (
  '${escapeSql(id)}', '${TENANT_ID}', '${SITE_ID}',
  '${escapeSql(ost.typeCode)}', '${escapeSql(ost.code)}',
  '${escapeSql(ost.name)}', ${ost.sortOrder}
);`);
	}

	sqlParts.push("COMMIT;");
	return sqlParts.join("\n");
}

function loadJson(filename) {
	const path = resolve(seedsDir, filename);
	return JSON.parse(readFileSync(path, "utf8"));
}

function escapeSql(str) {
	if (str === null || str === undefined) return "";
	return String(str).replace(/'/g, "''");
}

function readFlagValue(rest, flag) {
	const index = rest.indexOf(flag);
	if (index === -1) return null;
	return rest[index + 1] ?? null;
}

function printHelp() {
	process.stdout.write("Usage:\n");
	process.stdout.write("  node scripts/sikesra-seed.mjs apply --database <name> [--remote] [--execute]\n");
	process.stdout.write("  node scripts/sikesra-seed.mjs sql\n");
}
